---
## Author
author:
  name: Иванова Анастасия Сергеевна 
  degrees: DSc
  orcid: 0000-0002-0877-7063
  email: 1132250427@rudn.ru
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      postal-code: 117198
      city: Москва
      address: ул. Миклухо-Маклая, д. 6

## Title
title: "Отчет по лабораторной работе №4"
license: "CC BY"
---

# Цель работы
Освоение процедуры компиляции и сборки программ, написанных на ассемблере NASM.
# Выполнение лабораторной работы
1.Программа Hello world!
Рассмотрим пример простой программы на языке ассемблера NASM. Традиционно первая
программа выводит приветственное сообщение Hello world! на экран.
Создайте каталог для работы с программами на языке ассемблера NASM и перейдите в созданный каталог:

Создайте текстовый файл с именем hello.asm и откройте этот файл с помощью любого текстового редактора, например, gedit:

введем в него необходимый текст:

2.Транслятор NASM
NASM превращает текст программы в объектный код. Например, для компиляции приве-
дённого выше текста программы «Hello World» необходимо написать:

Если текст программы набран без ошибок, то транслятор преобразует текст программы
из файла hello.asm в объектный код, который запишется в файл hello.o. 
С помощью команды ls проверьте, что объектный файл был создан. 


# Вывод

::: {#refs}
:::
